[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py crear_superusuario_auto && gunicorn creditos.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Tareas programadas (cron jobs)
[cron]
# Generar tareas de cobro todos los días a las 6:00 AM (hora del servidor)
"0 6 * * 1-5" = "python manage.py generar_tareas_diarias --verbose"

# Análisis de cartera todos los días a las 11:59 PM
"59 23 * * *" = "python manage.py analizar_cartera_diario"

# Respaldo de base de datos cada domingo a las 3:00 AM
"0 3 * * 0" = "python manage.py dumpdata --format=json > backups/backup_$(date +%Y%m%d).json"