# Generated by Django 5.2.4 on 2025-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('DESEMBOLSADO', 'Desembolsado'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('VENCIDO', 'Vencido')], default='SOLICITADO', max_length=15),
        ),
    ]
