# Generated by Django 5.2.4 on 2025-09-16 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_credito_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(default='', max_length=100, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', max_length=15, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_cedula_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/', verbose_name='Cédula - Frente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_cedula_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/cedulas/', verbose_name='Cédula - Atrás'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_recibo_servicio',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/servicios/', verbose_name='Recibo de servicio público'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_rostro',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/rostros/', verbose_name='Foto del rostro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia1_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia 1 - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia1_telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Referencia 1 - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia2_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia 2 - Nombre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='referencia2_telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Referencia 2 - Teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(default='', verbose_name='Dirección completa'),
        ),
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('direccion', models.TextField(verbose_name='Dirección completa')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('foto_rostro', models.ImageField(blank=True, null=True, upload_to='codeudores/rostros/', verbose_name='Foto del rostro')),
                ('foto_cedula_frontal', models.ImageField(blank=True, null=True, upload_to='codeudores/cedulas/', verbose_name='Cédula - Frente')),
                ('foto_cedula_trasera', models.ImageField(blank=True, null=True, upload_to='codeudores/cedulas/', verbose_name='Cédula - Atrás')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codeudor', to='main.cliente')),
            ],
        ),
    ]
