# Generated by Django 5.2.4 on 2025-09-18 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cliente_nombre_remove_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='cantidad_cuotas',
            field=models.IntegerField(default=1, verbose_name='Cantidad de cuotas'),
        ),
        migrations.AddField(
            model_name='credito',
            name='descripcion_pago',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del pago'),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_desembolso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desembolso'),
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total a pagar'),
        ),
        migrations.AddField(
            model_name='credito',
            name='tipo_plazo',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=10, verbose_name='Tipo de plazo'),
        ),
        migrations.AddField(
            model_name='credito',
            name='total_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total interés a pagar'),
        ),
        migrations.AddField(
            model_name='credito',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de cada cuota'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto del crédito'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='plazo_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plazo en meses (calculado)'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de interés (%)'),
        ),
        migrations.CreateModel(
            name='CronogramaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la cuota')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('PARCIAL', 'Pago Parcial')], default='PENDIENTE', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='main.credito')),
            ],
            options={
                'ordering': ['numero_cuota'],
                'unique_together': {('credito', 'numero_cuota')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cronogramapago', verbose_name='Cuota asociada'),
        ),
    ]
