# Generated by Django 5.2.4 on 2025-09-19 23:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_credito_cantidad_cuotas_credito_descripcion_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la ruta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la ruta')),
                ('barrios', models.TextField(verbose_name='Barrios incluidos (separados por comas)')),
                ('zona', models.CharField(blank=True, max_length=50, verbose_name='Zona/Sector')),
                ('activa', models.BooleanField(default=True, verbose_name='Ruta activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=2, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('celular', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Teléfono debe tener formato válido. Ej: +573001234567 o 3001234567', regex='^\\+?1?\\d{9,15}$')], verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección de residencia')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Cobrador activo')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión por cobro (%)')),
                ('meta_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Meta diaria de cobros')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
                ('rutas', models.ManyToManyField(related_name='cobradores', to='main.ruta', verbose_name='Rutas asignadas')),
            ],
            options={
                'verbose_name': 'Cobrador',
                'verbose_name_plural': 'Cobradores',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
        migrations.AddField(
            model_name='credito',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cobrador', verbose_name='Cobrador asignado'),
        ),
    ]
