# Generated by Django 5.2.4 on 2025-09-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agregar_cobradores_rutas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateField(auto_now_add=True, verbose_name='Fecha del análisis')),
                ('total_creditos_activos', models.IntegerField(default=0)),
                ('cartera_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cartera_al_dia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cartera_vencida', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('creditos_al_dia', models.IntegerField(default=0)),
                ('creditos_mora_temprana', models.IntegerField(default=0)),
                ('creditos_mora_alta', models.IntegerField(default=0)),
                ('creditos_mora_critica', models.IntegerField(default=0)),
                ('total_interes_moratorio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_cartera_vencida', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dias_mora_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pagos_del_dia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meta_cobranza_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_cumplimiento_meta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Análisis de Cartera',
                'verbose_name_plural': 'Análisis de Cartera',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.AddField(
            model_name='credito',
            name='dias_mora',
            field=models.IntegerField(default=0, verbose_name='Días de mora'),
        ),
        migrations.AddField(
            model_name='credito',
            name='estado_mora',
            field=models.CharField(choices=[('AL_DIA', 'Al día'), ('MORA_TEMPRANA', 'Mora temprana (1-30 días)'), ('MORA_ALTA', 'Mora alta (31-90 días)'), ('MORA_CRITICA', 'Mora crítica (+90 días)')], default='AL_DIA', max_length=20, verbose_name='Estado de mora'),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento calculada'),
        ),
        migrations.AddField(
            model_name='credito',
            name='interes_moratorio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Interés moratorio acumulado'),
        ),
        migrations.AddField(
            model_name='credito',
            name='tasa_mora',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Tasa de mora diaria (%)'),
        ),
    ]
