# Generated by Django 5.2.4 on 2025-09-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carteraanalisis_credito_dias_mora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeudor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Codeudor activo'),
        ),
    ]
