# Generated by Django 5.2.4 on 2025-09-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_codeudor_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha asignada')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COBRADO', 'Cobrado'), ('NO_ESTABA', 'Cliente no estaba'), ('NO_PUDO_PAGAR', 'No pudo pagar'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta - Mora crítica'), ('MEDIA', 'Media - Mora temprana'), ('BAJA', 'Baja - Al día')], default='BAJA', max_length=10)),
                ('orden_visita', models.IntegerField(default=1, verbose_name='Orden de visita en ruta')),
                ('fecha_visita', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de visita')),
                ('monto_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto cobrado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del cobrador')),
                ('intentos_cobro', models.IntegerField(default=0, verbose_name='Número de intentos')),
                ('fecha_reprogramacion', models.DateField(blank=True, null=True, verbose_name='Fecha reprogramada')),
                ('latitud', models.FloatField(blank=True, null=True, verbose_name='Latitud de visita')),
                ('longitud', models.FloatField(blank=True, null=True, verbose_name='Longitud de visita')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cobrador', verbose_name='Cobrador asignado')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cronogramapago', verbose_name='Cuota a cobrar')),
            ],
            options={
                'verbose_name': 'Tarea de Cobro',
                'verbose_name_plural': 'Tareas de Cobro',
                'ordering': ['fecha_asignacion', 'orden_visita', 'prioridad'],
                'unique_together': {('cuota', 'fecha_asignacion')},
            },
        ),
    ]
