# Generated by Django 5.2.4 on 2025-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tareacobro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacobro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COBRADO', 'Cobrado'), ('NO_ENCONTRADO', 'Cliente no encontrado'), ('NO_ESTABA', 'Cliente no estaba'), ('NO_PUDO_PAGAR', 'No pudo pagar'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
    ]
