# Generated by Django 5.2.4 on 2025-09-24 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tareacobro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(help_text='Entre 8 y 10 dígitos numéricos', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 8 y 10 dígitos numéricos', regex='^\\d{8,10}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(default='', help_text='10 dígitos empezando con 3 (ej: 3001234567)', max_length=15, validators=[django.core.validators.RegexValidator(message='El celular debe tener 10 dígitos y empezar con 3 (ej: 3001234567)', regex='^3[0-9]{9}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencia1_telefono',
            field=models.CharField(blank=True, help_text='Celular 10 dígitos (3xxxxxxxxx)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El celular debe tener 10 dígitos y empezar con 3 (ej: 3001234567)', regex='^3[0-9]{9}$')], verbose_name='Referencia 1 - Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencia2_telefono',
            field=models.CharField(blank=True, help_text='Celular 10 dígitos (3xxxxxxxxx)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El celular debe tener 10 dígitos y empezar con 3 (ej: 3001234567)', regex='^3[0-9]{9}$')], verbose_name='Referencia 2 - Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_fijo',
            field=models.CharField(blank=True, help_text='7-8 dígitos (ej: 6012345)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono fijo debe tener 7-8 dígitos (ej: 6012345)', regex='^[2-8][0-9]{6,7}$')], verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='cedula',
            field=models.CharField(help_text='Entre 8 y 10 dígitos numéricos (no puede repetirse)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 8 y 10 dígitos numéricos', regex='^\\d{8,10}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='celular',
            field=models.CharField(help_text='10 dígitos empezando con 3 (ej: 3001234567)', max_length=15, validators=[django.core.validators.RegexValidator(message='El celular debe tener 10 dígitos y empezar con 3 (ej: 3001234567)', regex='^3[0-9]{9}$')], verbose_name='Celular'),
        ),
    ]
