# Generated by Django 5.2.4 on 2025-09-25 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_validaciones_cedula_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(help_text='Entre 5 y 10 dígitos numéricos', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 5 y 10 dígitos numéricos', regex='^\\d{5,10}$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='codeudor',
            name='cedula',
            field=models.CharField(help_text='Entre 5 y 10 dígitos numéricos (no puede repetirse)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener entre 5 y 10 dígitos numéricos', regex='^\\d{5,10}$')], verbose_name='Cédula'),
        ),
    ]
