# Generated by Django 5.2.4 on 2026-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_actualizar_validacion_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento_habeas_data',
            field=models.FileField(blank=True, null=True, upload_to='habeas_data/clientes/', verbose_name='Autorización Habeas Data (PDF)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_autorizacion_habeas_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización Habeas Data'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='documento_habeas_data',
            field=models.FileField(blank=True, null=True, upload_to='habeas_data/codeudores/', verbose_name='Autorización Habeas Data (PDF)'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='codeudor',
            name='fecha_autorizacion_habeas_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha autorización Habeas Data'),
        ),
        migrations.CreateModel(
            name='HabeasDataOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('codeudor', 'Codeudor')], max_length=10)),
                ('objeto_id', models.PositiveIntegerField(help_text='ID del Cliente o Codeudor')),
                ('otp_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tipo', 'objeto_id'], name='main_habeas_tipo_66e924_idx'), models.Index(fields=['expires_at'], name='main_habeas_expires_df90f1_idx')],
            },
        ),
    ]
