# Generated by Django 5.2.4 on 2026-02-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_renovacion_cliente_renovacionotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='credito_retanqueado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credito_nuevo_por_retanqueo', to='main.credito', verbose_name='Crédito anterior (retanqueo)'),
        ),
        migrations.AddField(
            model_name='credito',
            name='monto_aplicado_credito_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto aplicado al crédito anterior en retanqueo'),
        ),
        migrations.AddIndex(
            model_name='pagareotp',
            index=models.Index(fields=['credito', 'tipo_firmante'], name='main_pagare_credito_faa619_idx'),
        ),
        migrations.AddIndex(
            model_name='pagareotp',
            index=models.Index(fields=['expires_at'], name='main_pagare_expires_f73524_idx'),
        ),
    ]
