# Generated by Django 5.2.4 on 2026-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_credito_retanqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='es_renovacion',
            field=models.BooleanField(default=False, verbose_name='Crédito por renovación (no requiere pagaré, sí doc. renovación)'),
        ),
    ]
