# Generated by Django 5.2.4 on 2026-02-15 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_credito_documento_retanqueo_retanqueootp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareacobro',
            name='motivo_reprogramacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo reprogramación'),
        ),
        migrations.AddField(
            model_name='tareacobro',
            name='usuario_ultima_accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_cobro_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario última acción'),
        ),
        migrations.CreateModel(
            name='TareaCobroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADA', 'Tarea creada'), ('COBRADO', 'Marcada como cobrada'), ('NO_ENCONTRADO', 'Cliente no encontrado'), ('NO_ESTABA', 'Cliente no estaba'), ('NO_PUDO_PAGAR', 'No pudo pagar'), ('REPROGRAMADO', 'Reprogramada'), ('CANCELADO', 'Cancelada')], max_length=20, verbose_name='Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('motivo_reprogramacion', models.CharField(blank=True, max_length=255)),
                ('monto_registrado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto (si aplica)')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.tareacobro', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log tarea de cobro',
                'verbose_name_plural': 'Logs tareas de cobro',
                'ordering': ['-fecha'],
            },
        ),
    ]
