# Generated by Django 5.2.4 on 2026-02-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auditoria_cobranza_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCobroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de cierre')),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto según sistema (lo que cobró)')),
                ('cantidad_pagos', models.IntegerField(default=0, verbose_name='Cantidad de pagos')),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto recibido (arqueo)')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia (recibido - esperado)')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de cierre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
                ('cobrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_diarios', to='main.cobrador')),
            ],
            options={
                'verbose_name': 'Cierre de cobro diario',
                'verbose_name_plural': 'Cierres de cobro diario',
                'ordering': ['-fecha', '-fecha_cierre'],
                'unique_together': {('cobrador', 'fecha')},
            },
        ),
    ]
