# Generated by Django 5.2.4 on 2026-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_cierre_cobro_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='codigo_renovacion',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Código documento renovación'),
        ),
        migrations.AddField(
            model_name='credito',
            name='documento_renovacion',
            field=models.FileField(blank=True, null=True, upload_to='renovaciones/creditos/', verbose_name='Documento de renovación firmado (PDF)'),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_firma_renovacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha firma documento renovación'),
        ),
    ]
